### ISSUE TITLE
Is there a new version for competion 2010-2015,for the robot had updated to V5,much of it does not match

### ISSUE THREAD

**Issue by kuhung** [northern-bites/nao-man#1]
It feels like this share is totally different from code released by Bhuman.I am a junior student learning for robocup SPL.This file gives me much ideal.But still,something had chaged after 6 years.It would be happy to see a newly version.Hope your reply!

**Comment by kmushegi** [comment]
Hi @kuhung this repository has not been updated in 7 years and contains a lot of legacy code. The current Northern Bites RoboCup Soccer Package can be found [here](https://github.com/northern-bites/nbites), however you will still find that the our code is very different from the one released by B-Human because we develop most of our systems ourselves. Hope this is helpful!
